### PR TITLE
Futurize!

### PR DESCRIPTION
**Pull request by chrisgorgo**
Python 2 and 3 compatibility

### CODE REVIEW

**Comment by vsoch** [comment]
Oh awesome!! :D I'll take a look at this tomorrow, I thought I used to have tests but it seems that Github ate them. This is so great !!

**Comment by chrisfilo** [comment]
https://circleci.com/gh/chrisfilo/pybraincompare/tree/enh%2Ffuturize

**Comment by chrisfilo** [comment]
Thanks. I tested it against NV and it seems to be working well. Let me know when the new release hits pypi.

**Comment by vsoch** [comment]
```bash
Writing pybraincompare-0.1.19/setup.cfg
Creating tar archive
removing 'pybraincompare-0.1.19' (and everything under it)
running upload
Submitting dist/pybraincompare-0.1.19.tar.gz to https://upload.pypi.org/legacy/
Server response (200): OK
```
:smiley_cat:

**Comment by vsoch** [comment]
...and just for the fun, given the name and nature of this PR I must add a fwoop, back from the past, one of my favorite lines of all time!

> from future import @satra

:)

**Pull request merged**
